// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	smtp "github.com/sonalys/letterme/email_ms/smtp"
)

// SessionManager is an autogenerated mock type for the SessionManager type
type SessionManager struct {
	mock.Mock
}

// HandleConnection provides a mock function with given fields: c, s
func (_m *SessionManager) HandleConnection(c net.Conn, s *smtp.Server) {
	_m.Called(c, s)
}

// Shutdown provides a mock function with given fields:
func (_m *SessionManager) Shutdown() <-chan bool {
	ret := _m.Called()

	var r0 <-chan bool
	if rf, ok := ret.Get(0).(func() <-chan bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bool)
		}
	}

	return r0
}
