// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "github.com/sonalys/letterme/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// WaitResponse provides a mock function with given fields: id
func (_m *Router) WaitResponse(id string) <-chan models.Response {
	ret := _m.Called(id)

	var r0 <-chan models.Response
	if rf, ok := ret.Get(0).(func(string) <-chan models.Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan models.Response)
		}
	}

	return r0
}
