linters-settings:
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  gocritic:
    color: true
    shorterErrLocation: true
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: info

linters:
  enable:
    - revive
    - megacheck
    - unconvert
    - goconst
    - misspell
    - unparam
    - gofmt
    - goimports
    - gocyclo
    - gocritic
    - govet
    - unused
    - prealloc
    - bodyclose
    - whitespace
    - gocognit

issues:
  exclude-use-default: false
  max-same-issues: 10
  exclude-rules:
    - path: mocks\.go
      linters:
        - gomnd
    - path: _test\.go
      linters:
        - revive
        - unused
        - goconst
        - bodyclose
    - path: gen\.go
      linters:
        - unused
        - gocritic
        - gocognit
        - gosimple
