// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Channel is an autogenerated mock type for the Channel type
type Channel struct {
	mock.Mock
}

// Ack provides a mock function with given fields: tag, ackBeforeReceiving
func (_m *Channel) Ack(tag uint64, ackBeforeReceiving bool) error {
	ret := _m.Called(tag, ackBeforeReceiving)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool) error); ok {
		r0 = rf(tag, ackBeforeReceiving)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Nack provides a mock function with given fields: tag, ackBeforeReceiving, requeue
func (_m *Channel) Nack(tag uint64, ackBeforeReceiving bool, requeue bool) error {
	ret := _m.Called(tag, ackBeforeReceiving, requeue)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool, bool) error); ok {
		r0 = rf(tag, ackBeforeReceiving, requeue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
