// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	messaging "github.com/sonalys/letterme/domain/messaging"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryHandler is an autogenerated mock type for the DeliveryHandler type
type DeliveryHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, d
func (_m *DeliveryHandler) Execute(ctx context.Context, d messaging.Delivery) {
	_m.Called(ctx, d)
}
