// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	messaging "github.com/sonalys/letterme/domain/messaging"
	mock "github.com/stretchr/testify/mock"
)

// RouterHandler is an autogenerated mock type for the RouterHandler type
type RouterHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, d
func (_m *RouterHandler) Execute(ctx context.Context, d messaging.Delivery) (interface{}, error) {
	ret := _m.Called(ctx, d)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, messaging.Delivery) interface{}); ok {
		r0 = rf(ctx, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, messaging.Delivery) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
